jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(c,a,d,b,e){return jQuery.easing[jQuery.easing.def](c,a,d,b,e)},easeInQuad:function(c,a,d,b,e){return b*(a/=e)*a+d},easeOutQuad:function(c,a,d,b,e){return-b*(a/=e)*(a-2)+d},easeInOutQuad:function(c,a,d,b,e){if((a/=e/2)<1)return b/2*a*a+d;return-b/2*(--a*(a-2)-1)+d},easeInCubic:function(c,a,d,b,e){return b*(a/=e)*a*a+d},easeOutCubic:function(c,a,d,b,e){return b*((a=a/e-1)*a*a+1)+d},easeInOutCubic:function(c,a,d,b,e){if((a/=e/2)<1)return b/
2*a*a*a+d;return b/2*((a-=2)*a*a+2)+d},easeInQuart:function(c,a,d,b,e){return b*(a/=e)*a*a*a+d},easeOutQuart:function(c,a,d,b,e){return-b*((a=a/e-1)*a*a*a-1)+d},easeInOutQuart:function(c,a,d,b,e){if((a/=e/2)<1)return b/2*a*a*a*a+d;return-b/2*((a-=2)*a*a*a-2)+d},easeInQuint:function(c,a,d,b,e){return b*(a/=e)*a*a*a*a+d},easeOutQuint:function(c,a,d,b,e){return b*((a=a/e-1)*a*a*a*a+1)+d},easeInOutQuint:function(c,a,d,b,e){if((a/=e/2)<1)return b/2*a*a*a*a*a+d;return b/2*((a-=2)*a*a*a*a+2)+d},easeInSine:function(c,
a,d,b,e){return-b*Math.cos(a/e*(Math.PI/2))+b+d},easeOutSine:function(c,a,d,b,e){return b*Math.sin(a/e*(Math.PI/2))+d},easeInOutSine:function(c,a,d,b,e){return-b/2*(Math.cos(Math.PI*a/e)-1)+d},easeInExpo:function(c,a,d,b,e){return a==0?d:b*Math.pow(2,10*(a/e-1))+d},easeOutExpo:function(c,a,d,b,e){return a==e?d+b:b*(-Math.pow(2,-10*a/e)+1)+d},easeInOutExpo:function(c,a,d,b,e){if(a==0)return d;if(a==e)return d+b;if((a/=e/2)<1)return b/2*Math.pow(2,10*(a-1))+d;return b/2*(-Math.pow(2,-10*--a)+2)+d},
easeInCirc:function(c,a,d,b,e){return-b*(Math.sqrt(1-(a/=e)*a)-1)+d},easeOutCirc:function(c,a,d,b,e){return b*Math.sqrt(1-(a=a/e-1)*a)+d},easeInOutCirc:function(c,a,d,b,e){if((a/=e/2)<1)return-b/2*(Math.sqrt(1-a*a)-1)+d;return b/2*(Math.sqrt(1-(a-=2)*a)+1)+d},easeInElastic:function(c,a,d,b,e){c=1.70158;var f=0,h=b;if(a==0)return d;if((a/=e)==1)return d+b;f||(f=e*0.3);if(h<Math.abs(b)){h=b;c=f/4}else c=f/(2*Math.PI)*Math.asin(b/h);return-(h*Math.pow(2,10*(a-=1))*Math.sin((a*e-c)*2*Math.PI/f))+d},easeOutElastic:function(c,
a,d,b,e){c=1.70158;var f=0,h=b;if(a==0)return d;if((a/=e)==1)return d+b;f||(f=e*0.3);if(h<Math.abs(b)){h=b;c=f/4}else c=f/(2*Math.PI)*Math.asin(b/h);return h*Math.pow(2,-10*a)*Math.sin((a*e-c)*2*Math.PI/f)+b+d},easeInOutElastic:function(c,a,d,b,e){c=1.70158;var f=0,h=b;if(a==0)return d;if((a/=e/2)==2)return d+b;f||(f=e*0.3*1.5);if(h<Math.abs(b)){h=b;c=f/4}else c=f/(2*Math.PI)*Math.asin(b/h);if(a<1)return-0.5*h*Math.pow(2,10*(a-=1))*Math.sin((a*e-c)*2*Math.PI/f)+d;return h*Math.pow(2,-10*(a-=1))*Math.sin((a*
e-c)*2*Math.PI/f)*0.5+b+d},easeInBack:function(c,a,d,b,e,f){if(f==undefined)f=1.70158;return b*(a/=e)*a*((f+1)*a-f)+d},easeOutBack:function(c,a,d,b,e,f){if(f==undefined)f=1.70158;return b*((a=a/e-1)*a*((f+1)*a+f)+1)+d},easeInOutBack:function(c,a,d,b,e,f){if(f==undefined)f=1.70158;if((a/=e/2)<1)return b/2*a*a*(((f*=1.525)+1)*a-f)+d;return b/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+d},easeInBounce:function(c,a,d,b,e){return b-jQuery.easing.easeOutBounce(c,e-a,0,b,e)+d},easeOutBounce:function(c,a,d,b,e){return(a/=
e)<1/2.75?b*7.5625*a*a+d:a<2/2.75?b*(7.5625*(a-=1.5/2.75)*a+0.75)+d:a<2.5/2.75?b*(7.5625*(a-=2.25/2.75)*a+0.9375)+d:b*(7.5625*(a-=2.625/2.75)*a+0.984375)+d},easeInOutBounce:function(c,a,d,b,e){if(a<e/2)return jQuery.easing.easeInBounce(c,a*2,0,b,e)*0.5+d;return jQuery.easing.easeOutBounce(c,a*2-e,0,b,e)*0.5+b*0.5+d}});
(function(c){c.fn.hoverIntent=function(a,d){var b={sensitivity:7,interval:50,timeout:0};b=c.extend(b,d?{over:a,out:d}:a);var e,f,h,n,g=function(m){e=m.pageX;f=m.pageY},i=function(m,j){j.hoverIntent_t=clearTimeout(j.hoverIntent_t);if(Math.abs(h-e)+Math.abs(n-f)<b.sensitivity){c(j).unbind("mousemove",g);j.hoverIntent_s=1;return b.over.apply(j,[m])}else{h=e;n=f;j.hoverIntent_t=setTimeout(function(){i(m,j)},b.interval)}},l=function(m){for(var j=(m.type=="mouseover"?m.fromElement:m.toElement)||m.relatedTarget;j&&
j!=this;)try{j=j.parentNode}catch(p){j=this}if(j==this)return false;var o=jQuery.extend({},m),k=this;if(k.hoverIntent_t)k.hoverIntent_t=clearTimeout(k.hoverIntent_t);if(m.type=="mouseover"){h=o.pageX;n=o.pageY;c(k).bind("mousemove",g);if(k.hoverIntent_s!=1)k.hoverIntent_t=setTimeout(function(){i(o,k)},b.interval)}else{c(k).unbind("mousemove",g);if(k.hoverIntent_s==1)k.hoverIntent_t=setTimeout(function(){k.hoverIntent_t=clearTimeout(k.hoverIntent_t);k.hoverIntent_s=0;b.out.apply(k,[o])},b.timeout)}};
return this.mouseover(l).mouseout(l)}})(jQuery);$(function(){$("body").removeClass("coda-slider-no-js");$(".coda-slider").children(".panel").hide().end().prepend('<p class="loading">Loading...<br />Loading...</p>')});var sliderCount=1;
$.fn.codaSlider=function(c){c=$.extend({autoHeight:true,autoHeightEaseDuration:1E3,autoHeightEaseFunction:"easeInOutExpo",autoSlide:false,autoSlideInterval:7E3,autoSlideStopWhenClicked:true,crossLinking:true,dynamicArrows:true,dynamicArrowLeftText:"&#171; left",dynamicArrowRightText:"right &#187;",dynamicTabs:true,dynamicTabsAlign:"center",dynamicTabsPosition:"top",externalTriggerSelector:"a.xtrig",firstPanelToLoad:1,panelTitleSelector:"h2.title",slideEaseDuration:1E3,slideEaseFunction:"easeInOutExpo"},
c);return this.each(function(){function a(l){if(c.autoHeight){panelHeight=$(".panel:eq("+l+")",b).height();b.animate({height:panelHeight},c.autoHeightEaseDuration,c.autoHeightEaseFunction)}}function d(){if(n==0||!c.autoSlideStopWhenClicked){if(g==f){var l=0;g=1}else{l=-(e*g);g+=1}a(g-1);b.siblings(".coda-nav").find("a").removeClass("current").parents("ul").find("li:eq("+(g-1)+") a").addClass("current");$(".panel-container",b).animate({marginLeft:l},c.slideEaseDuration,c.slideEaseFunction);setTimeout(d,
c.autoSlideInterval)}}var b=$(this);if(c.dynamicArrows){b.parent().addClass("arrows");b.before('<div class="coda-nav-left" id="coda-nav-left-'+sliderCount+'"><a href="#">'+c.dynamicArrowLeftText+"</a></div>");b.after('<div class="coda-nav-right" id="coda-nav-right-'+sliderCount+'"><a href="#">'+c.dynamicArrowRightText+"</a></div>")}var e=b.find(".panel").width(),f=b.find(".panel").size(),h=e*f,n=0;$(".panel",b).wrapAll('<div class="panel-container"></div>');$(".panel-container",b).css({width:h});
if(c.crossLinking&&location.hash&&parseInt(location.hash.slice(1))<=f){var g=parseInt(location.hash.slice(1)),i=-(e*(g-1));$(".panel-container",b).css({marginLeft:i})}else if(c.firstPanelToLoad!=1&&c.firstPanelToLoad<=f){g=c.firstPanelToLoad;i=-(e*(g-1));$(".panel-container",b).css({marginLeft:i})}else g=1;$("#coda-nav-left-"+sliderCount+" a").click(function(){n++;if(g==1){i=-(e*(f-1));a(f-1);g=f;b.siblings(".coda-nav").find("a.current").removeClass("current").parents("ul").find("li:last a").addClass("current")}else{g-=
1;a(g-1);i=-(e*(g-1));b.siblings(".coda-nav").find("a.current").removeClass("current").parent().prev().find("a").addClass("current")}$(".panel-container",b).animate({marginLeft:i},c.slideEaseDuration,c.slideEaseFunction);if(c.crossLinking)location.hash=g;return false});$("#coda-nav-right-"+sliderCount+" a").click(function(){n++;if(g==f){i=0;g=1;a(0);b.siblings(".coda-nav").find("a.current").removeClass("current").parents("ul").find("a:eq(0)").addClass("current")}else{i=-(e*g);a(g);g+=1;b.siblings(".coda-nav").find("a.current").removeClass("current").parent().next().find("a").addClass("current")}$(".panel-container",
b).animate({marginLeft:i},c.slideEaseDuration,c.slideEaseFunction);if(c.crossLinking)location.hash=g;return false});if(c.dynamicTabs){h='<div class="coda-nav" id="coda-nav-'+sliderCount+'"><ul></ul></div>';switch(c.dynamicTabsPosition){case "bottom":b.parent().append(h);break;default:b.parent().prepend(h)}ul=$("#coda-nav-"+sliderCount+" ul");$(".panel",b).each(function(l){ul.append('<li class="tab'+(l+1)+'"><a href="#'+(l+1)+'">'+$(this).find(c.panelTitleSelector).text()+"</a></li>")});navContainerWidth=
b.width()+b.siblings(".coda-nav-left").width()+b.siblings(".coda-nav-right").width();ul.parent().css({width:navContainerWidth});switch(c.dynamicTabsAlign){case "center":ul.css({width:($("li",ul).width()+2)*f});break;case "right":ul.css({"float":"right"})}}$("#coda-nav-"+sliderCount+" a").each(function(l){$(this).hoverIntent({over:function(){n++;$(this).addClass("current").parents("ul").find("a").not($(this)).removeClass("current");i=-(e*l);a(l);g=l+1;$(".panel-container",b).stop().animate({marginLeft:i},
c.slideEaseDuration,c.slideEaseFunction);if(!c.crossLinking)return false},out:function(){}})});$(c.externalTriggerSelector).each(function(){sliderCount==parseInt($(this).attr("rel").slice(12))&&$(this).hoverIntent({over:function(){n++;targetPanel=parseInt($(this).attr("href").slice(1));i=-(e*(targetPanel-1));a(targetPanel-1);g=targetPanel;b.siblings(".coda-nav").find("a").removeClass("current").parents("ul").find("li:eq("+(targetPanel-1)+") a").addClass("current");$(".panel-container",b).animate({marginLeft:i},
c.slideEaseDuration,c.slideEaseFunction);if(!c.crossLinking)return false},out:function(){}})});if(c.crossLinking&&location.hash&&parseInt(location.hash.slice(1))<=f)$("#coda-nav-"+sliderCount+" a:eq("+(location.hash.slice(1)-1)+")").addClass("current");else c.firstPanelToLoad!=1&&c.firstPanelToLoad<=f?$("#coda-nav-"+sliderCount+" a:eq("+(c.firstPanelToLoad-1)+")").addClass("current"):$("#coda-nav-"+sliderCount+" a:eq(0)").addClass("current");if(c.autoHeight){panelHeight=$(".panel:eq("+(g-1)+")",b).height();
b.css({height:panelHeight})}c.autoSlide&&b.ready(function(){setTimeout(d,c.autoSlideInterval)});$(".panel",b).show().end().find("p.loading").remove();b.removeClass("preload");sliderCount++})};
$(document).ready(function(){$("#coda-slider-1").codaSlider({autoSlide:true,autoSlideInterval:4E3,autoSlideStopWhenClicked:true,dynamicArrows:false,dynamicTabs:false,slideEaseDuration:600});$("a[href^='http']").attr("target","_blank")});